### ISSUE TITLE
Issue starting it

### ISSUE THREAD

**Issue by Kallamamran** [TheCompAce/Auto-GPT-Powershell#7]
DONE Download the AutoGPT_PS repository.
DONE Place the GPT-4 model file in the same directory as the AutoGPT.ps1 script.
DONE Run the AutoGPT.ps1 script.
DONE Select y to go to the Options.
STUCK -> Enter the Starting Prompt (If using OpenAI GPT 3.5 or higher, then you will also be asked for a System Prompt.)

I only have this, so I don't know how to enter a starting prompt?!

![image](https://user-images.githubusercontent.com/25354644/232708201-61fb69bd-ac37-4254-a4de-140e642fd9ff.png)

**Comment by Kallamamran** [comment]
![image](https://user-images.githubusercontent.com/25354644/232708064-4356b916-3721-42df-ad3d-56dca9bb17f2.png)

**Comment by TheCompAce** [comment]
Looking at the screenshots I see a couple problems. On the Options, if you have "Toggle Use ChatGPT" to false then it uses the "model" file , if set to true then you need a "OpenAI Key". On the Second screenshot it looks like you have "Toggle Use ChatGPT" enabled (becuase it should not ask for "Start System" unless you are using GPT-3.5 or GPT4) And you did not enter in a "Start Prompt" (same with "Start System", not required but more info always helps AIs.)  So I the responses you are seeing are because you asked the local AI and empty string "", so it is replying with acting like a broken computer, So you are in turn talking to the AI.  Side Note: If you do have "Toggle Use ChatGPT" disabled, and it is still ask for "Start System" then that is a bug, and will do a check to see if it happens.  I Also made some big updates after what looks to be running, so I might have already fixed it.  Regardless, I am going to mark this as fixed, as it seems to be working.   End Note: The offline AI sucks really bad at doing this type of work, consider it a place holder till a better model or system comes out.

**Comment by TheCompAce** [comment]
Marked as Completed. See Above.

**Comment by Kallamamran** [comment]
Yepp... Now it works!

![image](https://user-images.githubusercontent.com/25354644/232981975-4586e048-b98a-4903-94eb-b3b13b20b5e3.png)

Don't know what you did, but it seem to have fixed it!
